version: '3.9'

services:
  app:
    build: .
    container_name: service_protofolio_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html       # ⬅️ project kamu
      - /var/www/html/vendor  # ⬅️ opsi no.2 → vendor hanya milik container
    ports:
      - "8000:8000"
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    # command: tail -f /dev/null
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  mysql_data:


